services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pixelant\Interest\:
    resource: '../Classes/*'

  Pixelant\Interest\DataHandling\Operation\Event\Handler\DeferSysFileRecordOperationEventHandler:
    tags:
      - name: event.listener
        identifier: deferSysFileRecordOperation
        event: Pixelant\Interest\DataHandling\Operation\Event\BeforeRecordOperationEvent

  Pixelant\Interest\DataHandling\Operation\Event\Handler\DeferSysFileReferenceRecordOperationEventHandler:
    tags:
      - name: event.listener
        identifier: deferSysFileReferenceRecordOperation
        event: Pixelant\Interest\DataHandling\Operation\Event\BeforeRecordOperationEvent

  \Pixelant\Interest\DataHandling\Operation\Event\Handler\ProcessDeferredRecordOperationsEventHandler:
    tags:
      - name: event.listener
        identifier: processDeferredRecordOperations
        event: Pixelant\Interest\DataHandling\Operation\Event\AfterRecordOperationEvent
